extends: seediv_no_concept_cosine_full100.yaml

dataset:
  sessions: [1, 2, 3]
  session: 1
  processed_path: data/cache/seediv_lds_de_s123_T10_stride1.npz

logging:
  save_dir: results/seed_iv/no_concept_cosine_sessions123_full100
